### ISSUE TITLE
Change Intlk-(Sel/Sts) PV Names

### ISSUE THREAD

**Issue by fernandohds564** [lnls-dig/sinap-timing-epics-ioc#1]
A better name for the Interlock PVs would be ByPassIntlk-(Sel/Sts) instead of the current Intlk-(Sel/Sts).

This change would make it easier to understand the meaning of these PVs.

The PV would still be of `enum` type, but the states associated with it would be `Active` and `ByPass`.

**Comment by jlmais** [comment]
Solved by commit [https://github.com/lnls-dig/sinap-timing-epics-ioc/commit/87ee9ad305b95752fa3e470d82ef2422b9aa80bb](url)
