### ISSUE TITLE
Remove old Intlk-(Sel/Sts) PVs from OUT

### ISSUE THREAD

**Issue by fernandohds564** [lnls-dig/sinap-timing-epics-ioc#2]
Now that there are PVs to ByPass the interlock in the internal triggers of the `EVR` and `EVE`, it would be nice to remove the old PVs associated with the `OUT` channels of these devices.

**Comment by jlmais** [comment]
Solved by commit [https://github.com/lnls-dig/sinap-timing-epics-ioc/commit/87ee9ad305b95752fa3e470d82ef2422b9aa80bb](url)
