### ISSUE TITLE
Change Lantronix to TCP socket over UDP

### ISSUE THREAD

**Issue by mmdonatti** [lnls-dig/sinap-timing-epics-ioc#25]
Lantronix XPort is being configured to use UDP sockets as interface with epics-ioc communication. Change to TCP sockets may improve interface reliability

**Comment by mmdonatti** [comment]
Lantronix convertion from socket to UART includes headers identified by the FPGA. So, when change from Datagram0 to Datagram1 we must compensate this difference at high level communication, `.proto`.

See pull request #10 for further details about UDP Datagram1 and Datagram0.

**Comment by mmdonatti** [comment]
UDP sending header, reading status register:
Tx: 0x02, 0x0A, 0x0A, 0x0A, 0x79, 0x00, 0x0D, 0xBF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
Rx: 0x02, 0x0A, 0x0A, 0x0A, 0x79, 0x00, 0x0D, 0xFF, 0x00, 0x00
Rx	data	1.937183	8.2e-05	0x00
Rx	data	1.937271	8.2e-05	0x00
Rx	data	1.937359	8.2e-05	0x00
Rx	data	1.937447	8.2e-05	0x00
Rx	data	1.937535	8.2e-05	0x00
Rx	data	1.937623	8.2e-05	0x00
Rx	data	1.937711	8.2e-05	0x00
Rx	data	1.937799	8.2e-05	0x00
Rx	data	1.937887	8.2e-05	0x00
Rx	data	1.937975	8.2e-05	0x10

**Comment by mmdonatti** [comment]
IOC works fine as well. See [tcp-socket](https://github.com/lnls-dig/sinap-timing-epics-ioc/tree/tcp-socket) branch

**Comment by ericonr** [comment]
This is now done in the master branch, so we can close this issue. All that is missing is deployment.
