### ISSUE TITLE
DelayType PVs in OUT channels

### ISSUE THREAD

**Issue by fernandohds564** [lnls-dig/sinap-timing-epics-ioc#3]
Currently, when we want to set the Delay of the channels OUT of the EVE and EVR to be relative to the BucketList we need to set the `RFDelay-SP` PV to `31`.
This method is not very intuitive and it would be better to change it.

The addition of new PVs of `enum` type, `DelayType-(Sel/Sts)` with states `Fixed` and `Incr`, just like the PVs of the EVG Events, and the limitation of the `RFDelay-SP/RB` to a maximum value of `30` instead of `31` would address this functionality in a much more intuitive way.

**Comment by jlmais** [comment]
Solved by commit [https://github.com/lnls-dig/sinap-timing-epics-ioc/commit/87ee9ad305b95752fa3e470d82ef2422b9aa80bb](url)
Added RFDelayType PVs.
